name: dixit
description: Flutter version of Dixit Boardgame 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  provider: ^4.0.5+1
  rxdart: ^0.24.0

  # Widgets / UI
  flash: ^1.3.1
  flutter_blurhash: ^0.4.1
  photo_view: ^0.9.2
  flutter_xlider: ^3.3.1

  # Data management
  shared_preferences: ^0.5.7

  # Web
  http: ^0.12.1
  cloud_firestore: ^0.13.5

  # Others
  diacritic: ^0.1.1

  # Platform info
  device_id: ^0.2.0
  screen: ^0.0.5

dev_dependencies:
  build_runner: ^1.9.0
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
