name: dixit
description: Flutter version of Dixit Boardgame
version: 1.0.1+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  provider: ^5.0.0
  rxdart: ^0.26.0

  # Widgets / UI
  flash: ^1.5.2
  flutter_blurhash: ^0.6.0
  photo_view: ^0.11.1
  flutter_xlider: ^3.4.0

  # Data management
  shared_preferences: ^2.0.5

  # Web
  http: ^0.13.2
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.2
  cloud_firestore: ^1.0.7

  # Others
  diacritic: ^0.1.3
  intl: ^0.17.0
  timeago: ^3.0.2
  duration: ^3.0.6

  # Platform info
  platform_device_id: ^1.0.1
  screen: ^0.0.5  # TODO replace with wakelock ? see https://github.com/clovisnicolas/flutter_screen/issues/32
  vibration: ^1.7.3
  package_info: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
